=== hmrc/self-assessment-api-legacy/public/api/conf/1.0/schemas/Liability.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "RequestLiability",
  "type": "object",
  "properties": {
    "income": {
      "title": "Income",
      "description": "Income summary",
      "$ref": "liability/IncomeSummary.json"
    },
    "incomeTaxCalculations": {
      "title": "Income tax calculations",
      "description": "Income tax calculations",
      "$ref": "liability/IncomeTaxCalculations.json"
    },
    "otherCharges": {
      "title": "Other charges",
      "description": "Other charged",
      "$ref": "liability/OtherCharges.json"
    },
    "taxDeducted": {
      "title": "Tax deducted",
      "description": "Tax deducted",
      "$ref": "liability/TaxDeducted.json"
    },
    "totalTaxDue": {
      "title": "Total tax due",
      "description": "The total amount of tax due",
      "type": "number",
      "minimum": 0
    },
    "totalTaxOverpaid": {
      "title": "Total tax overpaid",
      "description": "The total amount of tax overpaid",
      "type": "number",
      "minimum": 0
    }
  },
  "additionalProperties": false
}

=== hmrc/self-assessment-api-legacy/public/api/conf/1.0/examples/liability/Liability.json
{
  "income":{
    "incomes":{
      "nonSavings":{
        "selfEmployment":[
          {
            "id":"self-employment-1",
            "taxableProfit":8200,
            "profit":10000
          },
          {
            "id":"self-employment-2",
            "taxableProfit":25000,
            "profit":28000
          }
        ],
        "ukProperties":[
          {
            "id":"property1",
            "profit":2000
          },
          {
            "id":"property2",
            "profit":1500
          }
        ],
        "furnishedHolidayLettings":[
          {
            "id":"furnished-holiday-letting-1",
            "profit":8200
          },
          {
            "id":"furnished-holiday-letting-2",
            "profit":25000
          }
        ]
      },
      "savings":{
        "fromUKBanksAndBuildingSocieties":[
          {
            "id":"interest-income-1",
            "totalInterest":100
          },
          {
            "id":"interest-income-2",
            "totalInterest":200
          }
        ]
      },
      "dividends":{
        "fromUKSources":[
          {
            "id":"dividend-income-1",
            "totalDividend":1000
          },
          {
            "id":"dividend-income-2",
            "totalDividend":2000
          }
        ]
      },
      "total":93039
    },
    "deductions":{
      "incomeTaxRelief":5000,
      "personalAllowance":9440,
      "retirementAnnuityContract":10000,
      "total":24440
    },
    "totalIncomeOnWhichTaxIsDue":80000
  },
  "incomeTaxCalculations":{
    "nonSavings":[
      {
        "taxBand":"basicRate",
        "taxableAmount":10000,
        "chargedAt":"20%",
        "tax":2000
      },
      {
        "taxBand":"higherRate",
        "taxableAmount":10000,
        "chargedAt":"40%",
        "tax":4000
      },
      {
        "taxBand":"additionalHigherRate",
        "taxableAmount":10000,
        "chargedAt":"45%",
        "tax":4500
      }
    ],
    "savings":[
      {
        "taxBand":"startingRate",
        "taxableAmount":10000,
        "chargedAt":"0%",
        "tax":0
      },
      {
        "taxBand":"nilRate",
        "taxableAmount":10000,
        "chargedAt":"0%",
        "tax":0
      },
      {
        "taxBand":"basicRate",
        "taxableAmount":10000,
        "chargedAt":"20%",
        "tax":2000
      },
      {
        "taxBand":"higherRate",
        "taxableAmount":10000,
        "chargedAt":"40%",
        "tax":4000
      },
      {
        "taxBand":"additionalHigherRate",
        "taxableAmount":10000,
        "chargedAt":"45%",
        "tax":4500
      }
    ],
    "dividends":[
      {
        "taxBand":"nilRate",
        "taxableAmount":10000,
        "chargedAt":"0%",
        "tax":0
      },
      {
        "taxBand":"basicRate",
        "taxableAmount":10000,
        "chargedAt":"20%",
        "tax":2000
      },
      {
        "taxBand":"higherRate",
        "taxableAmount":10000,
        "chargedAt":"40%",
        "tax":4000
      },
      {
        "taxBand":"additionalHigherRate",
        "taxableAmount":10000,
        "chargedAt":"45%",
        "tax":4500
      }
    ],
    "total":31500
  },
  "otherCharges":{
    "pensionSavings":[
      {
        "taxBand":"basicRate",
        "taxableAmount":10000,
        "chargedAt":"20%",
        "tax":2000
      },
      {
        "taxBand":"higherRate",
        "taxableAmount":10000,
        "chargedAt":"40%",
        "tax":4000
      },
      {
        "taxBand":"additionalHigherRate",
        "taxableAmount":10000,
        "chargedAt":"45%",
        "tax":4500
      }
    ],
    "total":10500
  },
  "taxDeducted":{
    "interestFromUk":0,
    "taxPaidByPensionScheme":10500,
    "fromUkProperties":[
      {
        "id": "uk-properties-1",
        "taxPaid": 500.55
      }
    ],
    "total":0
  },
  "totalTaxDue":25796.95,
  "totalTaxOverpaid":0
}
