=== hmrc/self-assessment-api-legacy/public/api/conf/1.0/schemas/UK_PROP_OTHER_Period_Without_ID.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "title": "Period",
    "properties": {
        "from": {
            "title": "From date",
            "type": "string",
            "format": "date"
        },
        "to": {
            "title": "To date",
            "type": "string",
            "format": "date"
        },
        "incomes": {
            "$ref": "uk-properties/other/Incomes.json"
        },
        "expenses": {
            "$ref": "uk-properties/Expenses.json"
        }
    },
    "required": [
        "from",
        "to"
    ],
    "additionalProperties": false
}

=== hmrc/self-assessment-api-legacy/public/api/conf/1.0/examples/uk-properties/other/Period2.json
{
  "from": "2017-04-06",
  "to": "2017-07-04",
  "incomes": {
    "rentIncome": {
      "amount": 100.25,
      "taxDeducted": 100.25
    },
    "premiumsOfLeaseGrant": { "amount": 100.25 },
    "reversePremiums": { "amount": 100.25 }
  },
  "expenses": {
    "consolidatedExpenses": { "amount": 200.25 },
    "residentialFinancialCost": { "amount": 200.25 }
  }
}

=== hmrc/self-assessment-api-legacy/public/api/conf/1.0/examples/uk-properties/fhl/Period.json
{
  "from": "2017-04-06",
  "to": "2017-07-04",
  "incomes": {
    "rentIncome": {
      "amount": 100.25
    }
  },
  "expenses": {
    "premisesRunningCosts": { "amount": 100.25 },
    "repairsAndMaintenance": { "amount": 100.25 },
    "financialCosts": { "amount": 100.25 },
    "professionalFees": { "amount": 100.25 },
    "other": { "amount": 100.25 }
  }
}

=== hmrc/self-assessment-api-legacy/public/api/conf/1.0/examples/uk-properties/other/Period.json
{
  "from": "2017-04-06",
  "to": "2017-07-04",
  "incomes": {
    "rentIncome": {
      "amount": 100.25,
      "taxDeducted": 100.25
    },
    "premiumsOfLeaseGrant": { "amount": 100.25 },
    "reversePremiums": { "amount": 100.25 }
  },
  "expenses": {
    "premisesRunningCosts": { "amount": 100.25 },
    "repairsAndMaintenance": { "amount": 100.25 },
    "financialCosts": { "amount": 100.25 },
    "professionalFees": { "amount": 100.25 },
    "costOfServices": { "amount": 100.25 },
    "other": { "amount": 100.25 }
  }
}
