=== hmrc/self-assessment-api-legacy/resources/public/api/conf/1.0/schemas/retrieve-liability.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "_links": {
      "type": "object",
      "properties": {
        "self": {
          "type": "object",
          "properties": {
            "href": {
              "type": "string"
            }
          },
          "required": [ "href" ]
        }
      },
      "required": [ "self" ]
    },
    "income": {
      "type": "object",
      "properties": {
        "incomes": {
          "type": "object",
          "properties": {
            "nonSavings": {
              "type": "object",
              "properties": {
                "employment": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/nonSavingsIncomeSource"
                  }
                },
                "selfEmployment": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/nonSavingsIncomeSource"
                  }
                },
                "ukProperties": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/nonSavingsIncomeSource"
                  }
                },
                "furnishedHolidayLettings": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/nonSavingsIncomeSource"
                  }
                }
              },
              "required": [
                "employment",
                "selfEmployment",
                "ukProperties",
                "furnishedHolidayLettings"
              ]
            },
            "savings": {
              "type": "object",
              "properties": {
                "fromUKBanksAndBuildingSocieties": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/savingsIncomeSource"
                  }
                }
              },
              "required": [
                "fromUKBanksAndBuildingSocieties"
              ]
            },
            "dividends": {
              "type": "object",
              "properties": {
                "fromUKSources": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "sourceId": {
                        "type": "string"
                      },
                      "totalDividend": {
                        "description": "totalDividend is sum of all dividends from UK sources.",
                        "type": "number"
                      }
                    },
                    "required": [
                      "sourceId",
                      "totalDividend"
                    ]
                  }
                }
              },
              "required": [
                "fromUKSources"
              ]
            },
            "total": {
              "type": "number"
            }
          },
          "required": [
            "nonSavings",
            "savings",
            "dividends",
            "total"
          ]
        },
        "deductions": {
          "type": "object",
          "properties": {
            "incomeTaxRelief": {
              "description": "incomeTaxRelief is Sum of all losses brought forward.",
              "type": "number"
            },
            "personalAllowance": {
              "description": "This is the annual personal allowance the taxpayer is entitled to. This is currently a maximum of Â£11,000 for the tax year. Note, Personal Allowance may be reduced/tapered dependent on the value of total income.",
              "type": "number"
            },
            "retirementAnnuityContract": {
              "type": "number"
            },
            "total": {
              "type": "number"
            }
          },
          "required": [
            "incomeTaxRelief",
            "personalAllowance",
            "retirementAnnuityContract",
            "total"
          ]
        },
        "totalIncomeOnWhichTaxIsDue": {
          "description": "This is the total income on which tax is due after reliefs and allowances have been deducted (Total Income Received minus Total deductions).",
          "type": "number"
        }
      },
      "required": [
        "incomes",
        "deductions",
        "totalIncomeOnWhichTaxIsDue"
      ]
    },
    "incomeTaxCalculations": {
      "type": "object",
      "properties": {
        "nonSavings": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/taxCalculation"
          }
        },
        "savings": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/taxCalculation"
          }
        },
        "dividends": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/taxCalculation"
          }
        },
        "total": {
          "type": "number"
        }
      },
      "required": [
        "nonSavings",
        "savings",
        "dividends",
        "total"
      ]
    },
    "otherCharges": {
      "type": "object",
      "properties": {
        "pensionSavings": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "taxBand": {
                "type": "string"
              },
              "taxableAmount": {
                "type": "number"
              },
              "chargedAt": {
                "type": "string"
              },
              "tax": {
                "type": "number"
              }
            },
            "required": [
              "taxBand",
              "taxableAmount",
              "chargedAt",
              "tax"
            ]
          }
        },
        "total": {
          "type": "number"
        }
      },
      "required": [
        "pensionSavings",
        "total"
      ]
    },
    "taxDeducted": {
      "type": "object",
      "properties": {
        "interestFromUk": {
          "description": "Grossed-up Taxed interest that the tax payer received minus taxed interest",
          "type": "number"
        },
        "taxPaidByPensionScheme": {
          "type": "number"
        },
        "fromUkProperties": {
          "type": "array",
          "items": {}
        },
        "fromEmployments": {
          "type": "array",
          "items": {}
        },
        "total": {
          "type": "number"
        }
      },
      "required": [
        "interestFromUk",
        "taxPaidByPensionScheme",
        "fromUkProperties",
        "fromEmployments",
        "total"
      ]
    },
    "totalTaxDue": {
      "description": "Total Income Tax minus Total Tax Deductions (if it is positive)",
      "type": "number"
    },
    "totalTaxOverpaid": {
      "description": "Total Income Tax minus Total Tax Deductions (if it is negative)",
      "type": "number"
    }
  },
  "required": [
    "_links",
    "income",
    "incomeTaxCalculations",
    "otherCharges",
    "taxDeducted",
    "totalTaxDue",
    "totalTaxOverpaid"
  ],
  "definitions": {
    "nonSavingsIncomeSource": {
      "type": "object",
      "properties": {
        "sourceId": {
          "type": "string"
        },
        "taxableProfit": {
          "description": "Total taxable profit for the current year which is total earnings + balancing charges + disallowable expenses + goods used for own use minus (allowable expenses + capital allowances)",
          "type": "number"
        },
        "profit": {
          "description": "taxableProfit plus losses brought forward.",
          "type": "number"
        }
      },
      "required": [ "sourceId" ]
    },
    "savingsIncomeSource": {
      "type": "object",
      "properties": {
        "sourceId": {
          "type": "string"
        },
        "totalInterest": {
          "description": "totalInterest is Grossed-up Taxed Interest plus Untaxed Interest.",
          "type": "number"
        }
      },
      "required": [ "sourceId" ]
    },
    "taxCalculation": {
      "type": "object",
      "properties": {
        "taxBand": {
          "description": "To indicate whether the calculation is for basic rate band or higher rate band or additional higher rate band. In Savings and Dividends income case, the tax band also includes the Starting Rate Band and Nil Rate bands.",
          "type": "string"
        },
        "taxableAmount": {
          "description": "Total Taxable Income on which the rate band and tax rate is applied.",
          "type": "number"
        },
        "chargedAt": {
          "description": "Tax percentage that is applied depending upon the band.",
          "type": "string"
        },
        "tax": {
          "type": "number"
        }
      },
      "required": [
        "taxBand",
        "taxableAmount",
        "chargedAt",
        "tax"
      ]
    }
  }
}

=== hmrc/self-assessment-api-legacy/resources/public/api/conf/1.0/examples/retrieve-liability-example-1.json
{
  "_links" : {
    "self" : {
      "href" : "/self-assessment/2234567890/2016-17/liability"
    }
  },
  "income" : {
    "incomes" : {
      "nonSavings" : {
        "employment" : [ {
          "sourceId" : "employment-1",
          "pay" : 1000,
          "benefitsAndExpenses" : 500,
          "allowableExpenses" : 250,
          "total" : 1250
        }, {
          "sourceId" : "employment-2",
          "pay" : 2000,
          "benefitsAndExpenses" : 1000,
          "allowableExpenses" : 500,
          "total" : 2500
        } ],
        "selfEmployment" : [ {
          "sourceId" : "self-employment-1",
          "taxableProfit" : 8200,
          "profit" : 10000
        }, {
          "sourceId" : "self-employment-2",
          "taxableProfit" : 25000,
          "profit" : 28000
        } ],
        "ukProperties" : [ {
          "sourceId" : "property1",
          "profit" : 2000
        }, {
          "sourceId" : "property2",
          "profit" : 1500
        } ],
        "furnishedHolidayLettings" : [ {
          "sourceId" : "furnished-holiday-letting-1",
          "profit" : 8200
        }, {
          "sourceId" : "furnished-holiday-letting-2",
          "profit" : 25000
        } ]
      },
      "savings" : {
        "fromUKBanksAndBuildingSocieties" : [ {
          "sourceId" : "interest-income-1",
          "totalInterest" : 100
        }, {
          "sourceId" : "interest-income-2",
          "totalInterest" : 200
        } ]
      },
      "dividends" : {
        "fromUKSources" : [ {
          "sourceId" : "dividend-income-1",
          "totalDividend" : 1000
        }, {
          "sourceId" : "dividend-income-2",
          "totalDividend" : 2000
        } ]
      },
      "total" : 93039
    },
    "deductions" : {
      "incomeTaxRelief" : 5000,
      "personalAllowance" : 9440,
      "retirementAnnuityContract" : 10000,
      "total" : 24440
    },
    "totalIncomeOnWhichTaxIsDue" : 80000
  },
  "incomeTaxCalculations" : {
    "nonSavings" : [ {
      "taxBand" : "basicRate",
      "taxableAmount" : 10000,
      "chargedAt" : "20%",
      "tax" : 2000
    }, {
      "taxBand" : "higherRate",
      "taxableAmount" : 10000,
      "chargedAt" : "40%",
      "tax" : 4000
    }, {
      "taxBand" : "additionalHigherRate",
      "taxableAmount" : 10000,
      "chargedAt" : "45%",
      "tax" : 4500
    } ],
    "savings" : [ {
      "taxBand" : "startingRate",
      "taxableAmount" : 10000,
      "chargedAt" : "0%",
      "tax" : 0
    }, {
      "taxBand" : "nilRate",
      "taxableAmount" : 10000,
      "chargedAt" : "0%",
      "tax" : 0
    }, {
      "taxBand" : "basicRate",
      "taxableAmount" : 10000,
      "chargedAt" : "20%",
      "tax" : 2000
    }, {
      "taxBand" : "higherRate",
      "taxableAmount" : 10000,
      "chargedAt" : "40%",
      "tax" : 4000
    }, {
      "taxBand" : "additionalHigherRate",
      "taxableAmount" : 10000,
      "chargedAt" : "45%",
      "tax" : 4500
    } ],
    "dividends" : [ {
      "taxBand" : "nilRate",
      "taxableAmount" : 10000,
      "chargedAt" : "0%",
      "tax" : 0
    }, {
      "taxBand" : "basicRate",
      "taxableAmount" : 10000,
      "chargedAt" : "20%",
      "tax" : 2000
    }, {
      "taxBand" : "higherRate",
      "taxableAmount" : 10000,
      "chargedAt" : "40%",
      "tax" : 4000
    }, {
      "taxBand" : "additionalHigherRate",
      "taxableAmount" : 10000,
      "chargedAt" : "45%",
      "tax" : 4500
    } ],
    "total" : 31500
  },
  "otherCharges" : {
    "pensionSavings" : [ {
      "taxBand" : "basicRate",
      "taxableAmount" : 10000,
      "chargedAt" : "20%",
      "tax" : 2000
    }, {
      "taxBand" : "higherRate",
      "taxableAmount" : 10000,
      "chargedAt" : "40%",
      "tax" : 4000
    }, {
      "taxBand" : "additionalHigherRate",
      "taxableAmount" : 10000,
      "chargedAt" : "45%",
      "tax" : 4500
    } ],
    "total" : 10500
  },
  "taxDeducted" : {
    "interestFromUk" : 0,
    "taxPaidByPensionScheme" : 10500,
    "fromUkProperties" : [ ],
    "fromEmployments" : [ {
      "sourceId" : "employment-1",
      "taxPaid" : 4000
    }, {
      "sourceId" : "employment-2",
      "taxPaid" : 5000
    } ],
    "total" : 0
  },
  "totalTaxDue" : 25796.95,
  "totalTaxOverpaid" : 0
}
